/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void dashboard_draw(PApplet appc, GWinData data) { //_CODE_:dashboard:659053:
  appc.background(230);
} //_CODE_:dashboard:659053:

public void toUserInfoTab_click(GButton source, GEvent event) { //_CODE_:toUserInfoTab:777504:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:toUserInfoTab:777504:

synchronized public void userInfoTab_draw(PApplet appc, GWinData data) { //_CODE_:userInfoTab:277410:
  appc.background(230);
} //_CODE_:userInfoTab:277410:

public void toDashboardButton_click(GButton source, GEvent event) { //_CODE_:toDashboardButton:550522:
  println("userInfoTab4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:toDashboardButton:550522:

public void ageField_type(GTextField source, GEvent event) { //_CODE_:ageField:391582:
  println("ageField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:ageField:391582:

public void userHeightField_type(GTextField source, GEvent event) { //_CODE_:userHeightField:796273:
  println("userHeightField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:userHeightField:796273:

public void userWeightField_type(GTextField source, GEvent event) { //_CODE_:userWeightField:689910:
  println("userWeightField - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:userWeightField:689910:

public void sexField_click(GDropList source, GEvent event) { //_CODE_:sexField:731036:
  println("sexField - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:sexField:731036:

public void saveUserInfoButton_click(GButton source, GEvent event) { //_CODE_:saveUserInfoButton:890613:
  println("saveUserInfoButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:saveUserInfoButton:890613:

public void resetUserInfoButton_click(GButton source, GEvent event) { //_CODE_:resetUserInfoButton:534489:
  println("resetUserInfoButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:resetUserInfoButton:534489:

public void goalList_click(GDropList source, GEvent event) { //_CODE_:goalList:466574:
  println("goalList - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:goalList:466574:

public void isVegetarian_click(GCheckbox source, GEvent event) { //_CODE_:isVegetarian:287580:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isVegetarian:287580:

public void isVegan_click(GCheckbox source, GEvent event) { //_CODE_:isVegan:968256:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isVegan:968256:

public void isHalal_click(GCheckbox source, GEvent event) { //_CODE_:isHalal:254714:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isHalal:254714:

public void isPescetarian_click(GCheckbox source, GEvent event) { //_CODE_:isPescetarian:998524:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isPescetarian:998524:

public void isGlutenFree_click(GCheckbox source, GEvent event) { //_CODE_:isGlutenFree:368552:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isGlutenFree:368552:

public void isNutAllergy_click(GCheckbox source, GEvent event) { //_CODE_:isNutAllergy:563699:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isNutAllergy:563699:

public void isLactoseIntolerant_click(GCheckbox source, GEvent event) { //_CODE_:isLactoseIntolerant:504553:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isLactoseIntolerant:504553:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  dashboard = GWindow.getWindow(this, "Dashboard", 0, 0, 400, 300, JAVA2D);
  dashboard.noLoop();
  dashboard.setActionOnClose(G4P.KEEP_OPEN);
  dashboard.addDrawHandler(this, "dashboard_draw");
  toUserInfoTab = new GButton(dashboard, 130, 160, 140, 30);
  toUserInfoTab.setText("Modify User Info >");
  toUserInfoTab.addEventHandler(this, "toUserInfoTab_click");
  welcomeMessage = new GLabel(dashboard, 90, 120, 220, 20);
  welcomeMessage.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  welcomeMessage.setText("Welcome to the FuelWell dashboard.");
  welcomeMessage.setOpaque(false);
  userInfoTab = GWindow.getWindow(this, "userInfo", 0, 0, 400, 300, JAVA2D);
  userInfoTab.noLoop();
  userInfoTab.setActionOnClose(G4P.KEEP_OPEN);
  userInfoTab.addDrawHandler(this, "userInfoTab_draw");
  toDashboardButton = new GButton(userInfoTab, 11, 12, 140, 30);
  toDashboardButton.setText("< Back to Dashboard");
  toDashboardButton.addEventHandler(this, "toDashboardButton_click");
  ageLabel = new GLabel(userInfoTab, 12, 79, 80, 20);
  ageLabel.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  ageLabel.setText("Age:");
  ageLabel.setOpaque(false);
  sexLabel = new GLabel(userInfoTab, 11, 104, 80, 20);
  sexLabel.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  sexLabel.setText("Sex:");
  sexLabel.setOpaque(false);
  userHeightLabel = new GLabel(userInfoTab, 13, 129, 80, 20);
  userHeightLabel.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  userHeightLabel.setText("Height (cm):");
  userHeightLabel.setOpaque(false);
  userWeightLabel = new GLabel(userInfoTab, 14, 153, 80, 20);
  userWeightLabel.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  userWeightLabel.setText("Weight (kg):");
  userWeightLabel.setOpaque(false);
  ageField = new GTextField(userInfoTab, 99, 79, 40, 20, G4P.SCROLLBARS_NONE);
  ageField.setOpaque(true);
  ageField.addEventHandler(this, "ageField_type");
  userHeightField = new GTextField(userInfoTab, 99, 132, 60, 20, G4P.SCROLLBARS_NONE);
  userHeightField.setOpaque(true);
  userHeightField.addEventHandler(this, "userHeightField_type");
  userWeightField = new GTextField(userInfoTab, 100, 156, 50, 20, G4P.SCROLLBARS_NONE);
  userWeightField.setOpaque(true);
  userWeightField.addEventHandler(this, "userWeightField_type");
  sexField = new GDropList(userInfoTab, 98, 106, 70, 60, 2, 10);
  sexField.setItems(loadStrings("list_731036"), 0);
  sexField.addEventHandler(this, "sexField_click");
  saveUserInfoButton = new GButton(userInfoTab, 206, 246, 120, 30);
  saveUserInfoButton.setText("Save User Info");
  saveUserInfoButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  saveUserInfoButton.addEventHandler(this, "saveUserInfoButton_click");
  resetUserInfoButton = new GButton(userInfoTab, 64, 246, 120, 30);
  resetUserInfoButton.setText("Reset User Info");
  resetUserInfoButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  resetUserInfoButton.addEventHandler(this, "resetUserInfoButton_click");
  goalLabel = new GLabel(userInfoTab, 208, 25, 50, 20);
  goalLabel.setTextAlign(GAlign.RIGHT, GAlign.MIDDLE);
  goalLabel.setText("Goal:");
  goalLabel.setOpaque(false);
  goalList = new GDropList(userInfoTab, 259, 27, 90, 100, 4, 10);
  goalList.setItems(loadStrings("list_466574"), 0);
  goalList.addEventHandler(this, "goalList_click");
  dietaryRestrictionsLabel = new GLabel(userInfoTab, 206, 55, 130, 20);
  dietaryRestrictionsLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  dietaryRestrictionsLabel.setText("Dietary Restrictions:");
  dietaryRestrictionsLabel.setOpaque(false);
  isVegetarian = new GCheckbox(userInfoTab, 213, 78, 120, 20);
  isVegetarian.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isVegetarian.setText("Vegetarian");
  isVegetarian.setOpaque(false);
  isVegetarian.addEventHandler(this, "isVegetarian_click");
  isVegan = new GCheckbox(userInfoTab, 213, 98, 120, 20);
  isVegan.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isVegan.setText("Vegan");
  isVegan.setOpaque(false);
  isVegan.addEventHandler(this, "isVegan_click");
  isHalal = new GCheckbox(userInfoTab, 213, 119, 120, 20);
  isHalal.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isHalal.setText("Halal");
  isHalal.setOpaque(false);
  isHalal.addEventHandler(this, "isHalal_click");
  isPescetarian = new GCheckbox(userInfoTab, 212, 140, 120, 20);
  isPescetarian.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isPescetarian.setText("Pescetarian");
  isPescetarian.setOpaque(false);
  isPescetarian.addEventHandler(this, "isPescetarian_click");
  isGlutenFree = new GCheckbox(userInfoTab, 212, 161, 120, 20);
  isGlutenFree.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isGlutenFree.setText("Gluten Free");
  isGlutenFree.setOpaque(false);
  isGlutenFree.addEventHandler(this, "isGlutenFree_click");
  isNutAllergy = new GCheckbox(userInfoTab, 213, 182, 120, 20);
  isNutAllergy.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isNutAllergy.setText("Nut Allergy");
  isNutAllergy.setOpaque(false);
  isNutAllergy.addEventHandler(this, "isNutAllergy_click");
  isLactoseIntolerant = new GCheckbox(userInfoTab, 211, 202, 120, 20);
  isLactoseIntolerant.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isLactoseIntolerant.setText("Lactose Intolerant");
  isLactoseIntolerant.setOpaque(false);
  isLactoseIntolerant.addEventHandler(this, "isLactoseIntolerant_click");
  dashboard.loop();
  userInfoTab.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow dashboard;
GButton toUserInfoTab; 
GLabel welcomeMessage; 
GWindow userInfoTab;
GButton toDashboardButton; 
GLabel ageLabel; 
GLabel sexLabel; 
GLabel userHeightLabel; 
GLabel userWeightLabel; 
GTextField ageField; 
GTextField userHeightField; 
GTextField userWeightField; 
GDropList sexField; 
GButton saveUserInfoButton; 
GButton resetUserInfoButton; 
GLabel goalLabel; 
GDropList goalList; 
GLabel dietaryRestrictionsLabel; 
GCheckbox isVegetarian; 
GCheckbox isVegan; 
GCheckbox isHalal; 
GCheckbox isPescetarian; 
GCheckbox isGlutenFree; 
GCheckbox isNutAllergy; 
GCheckbox isLactoseIntolerant; 
