/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void dashboard_draw(PApplet appc, GWinData data) { //_CODE_:dashboard:659053:
  appc.background(230);
} //_CODE_:dashboard:659053:

public void dietTab_click(GButton source, GEvent event) { //_CODE_:dietTab1:272039:
  println("dietTab - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dietTab1:272039:

public void dailyFoodRecsTab_click(GButton source, GEvent event) { //_CODE_:dailyFoodRecsTab1:304495:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dailyFoodRecsTab1:304495:

public void userInfoTab1_click(GButton source, GEvent event) { //_CODE_:userInfoTab1:777504:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:userInfoTab1:777504:

synchronized public void dietTab_draw(PApplet appc, GWinData data) { //_CODE_:dietTab:542480:
  appc.background(230);
} //_CODE_:dietTab:542480:

public void dietTab2_click(GButton source, GEvent event) { //_CODE_:dietTab2:792507:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dietTab2:792507:

public void dailyFoodRecsTab2_click(GButton source, GEvent event) { //_CODE_:dailyFoodRecsTab2:459038:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dailyFoodRecsTab2:459038:

public void userInfoTab2_click(GButton source, GEvent event) { //_CODE_:userInfoTab2:548673:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:userInfoTab2:548673:

synchronized public void dailyFoodRecsTab_draw(PApplet appc, GWinData data) { //_CODE_:dailyFoodRecsTab:661177:
  appc.background(230);
} //_CODE_:dailyFoodRecsTab:661177:

public void dietTab3_click(GButton source, GEvent event) { //_CODE_:dietTab3:605731:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dietTab3:605731:

public void dailyFoodRecsTab3_click(GButton source, GEvent event) { //_CODE_:dailyFoodRecsTab3:962101:
  println("dailyFoodRecsTab3 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dailyFoodRecsTab3:962101:

public void userInfoTab3_click(GButton source, GEvent event) { //_CODE_:userInfoTab3:760193:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:userInfoTab3:760193:

synchronized public void userInfoTab_draw(PApplet appc, GWinData data) { //_CODE_:userInfoTab:277410:
  appc.background(230);
} //_CODE_:userInfoTab:277410:

public void dietTab4_click(GButton source, GEvent event) { //_CODE_:dietTab4:226840:
  println("dietTab4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dietTab4:226840:

public void dailyFoodRecsTab4_click(GButton source, GEvent event) { //_CODE_:dailyFoodRecsTab4:894616:
  println("dailyFoodRecsTab4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:dailyFoodRecsTab4:894616:

public void userInfoTab4_click(GButton source, GEvent event) { //_CODE_:userInfoTab4:550522:
  println("userInfoTab4 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:userInfoTab4:550522:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  dashboard = GWindow.getWindow(this, "Dashboard", 0, 0, 400, 300, JAVA2D);
  dashboard.noLoop();
  dashboard.setActionOnClose(G4P.KEEP_OPEN);
  dashboard.addDrawHandler(this, "dashboard_draw");
  dietTab1 = new GButton(dashboard, 10, 20, 120, 30);
  dietTab1.setText("Diet");
  dietTab1.addEventHandler(this, "dietTab_click");
  dailyFoodRecsTab1 = new GButton(dashboard, 140, 20, 120, 30);
  dailyFoodRecsTab1.setText("Daily Food Recs");
  dailyFoodRecsTab1.addEventHandler(this, "dailyFoodRecsTab_click");
  userInfoTab1 = new GButton(dashboard, 270, 20, 120, 30);
  userInfoTab1.setText("User Info");
  userInfoTab1.addEventHandler(this, "userInfoTab1_click");
  dietTab = GWindow.getWindow(this, "Diet Tab", 0, 0, 400, 300, JAVA2D);
  dietTab.noLoop();
  dietTab.setActionOnClose(G4P.KEEP_OPEN);
  dietTab.addDrawHandler(this, "dietTab_draw");
  dietTab2 = new GButton(dietTab, 10, 20, 120, 30);
  dietTab2.setText("Diet");
  dietTab2.addEventHandler(this, "dietTab2_click");
  dailyFoodRecsTab2 = new GButton(dietTab, 140, 20, 120, 30);
  dailyFoodRecsTab2.setText("Daily Food Recs");
  dailyFoodRecsTab2.addEventHandler(this, "dailyFoodRecsTab2_click");
  userInfoTab2 = new GButton(dietTab, 270, 20, 120, 30);
  userInfoTab2.setText("User Info");
  userInfoTab2.addEventHandler(this, "userInfoTab2_click");
  dailyFoodRecsTab = GWindow.getWindow(this, "Daily Food Recs", 0, 0, 400, 300, JAVA2D);
  dailyFoodRecsTab.noLoop();
  dailyFoodRecsTab.setActionOnClose(G4P.KEEP_OPEN);
  dailyFoodRecsTab.addDrawHandler(this, "dailyFoodRecsTab_draw");
  dietTab3 = new GButton(dailyFoodRecsTab, 10, 20, 120, 30);
  dietTab3.setText("Diet");
  dietTab3.addEventHandler(this, "dietTab3_click");
  dailyFoodRecsTab3 = new GButton(dailyFoodRecsTab, 140, 20, 120, 30);
  dailyFoodRecsTab3.setText("Daily Food Recs");
  dailyFoodRecsTab3.addEventHandler(this, "dailyFoodRecsTab3_click");
  userInfoTab3 = new GButton(dailyFoodRecsTab, 270, 20, 120, 30);
  userInfoTab3.setText("User Info");
  userInfoTab3.addEventHandler(this, "userInfoTab3_click");
  userInfoTab = GWindow.getWindow(this, "userInfo", 0, 0, 400, 300, JAVA2D);
  userInfoTab.noLoop();
  userInfoTab.setActionOnClose(G4P.KEEP_OPEN);
  userInfoTab.addDrawHandler(this, "userInfoTab_draw");
  dietTab4 = new GButton(userInfoTab, 10, 20, 120, 30);
  dietTab4.setText("Diet");
  dietTab4.addEventHandler(this, "dietTab4_click");
  dailyFoodRecsTab4 = new GButton(userInfoTab, 140, 20, 120, 30);
  dailyFoodRecsTab4.setText("Daily Food Recs");
  dailyFoodRecsTab4.addEventHandler(this, "dailyFoodRecsTab4_click");
  userInfoTab4 = new GButton(userInfoTab, 270, 20, 120, 30);
  userInfoTab4.setText("User Info");
  userInfoTab4.addEventHandler(this, "userInfoTab4_click");
  dashboard.loop();
  dietTab.loop();
  dailyFoodRecsTab.loop();
  userInfoTab.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow dashboard;
GButton dietTab1; 
GButton dailyFoodRecsTab1; 
GButton userInfoTab1; 
GWindow dietTab;
GButton dietTab2; 
GButton dailyFoodRecsTab2; 
GButton userInfoTab2; 
GWindow dailyFoodRecsTab;
GButton dietTab3; 
GButton dailyFoodRecsTab3; 
GButton userInfoTab3; 
GWindow userInfoTab;
GButton dietTab4; 
GButton dailyFoodRecsTab4; 
GButton userInfoTab4; 
