/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:515557:
  appc.background(230);
} //_CODE_:window1:515557:

public void pescClicked(GCheckbox source, GEvent event) { //_CODE_:isPesc:816104:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isPesc:816104:

public void glutenClicked(GCheckbox source, GEvent event) { //_CODE_:isGluten:960924:
  println("checkbox2 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isGluten:960924:

public void nutClicked(GCheckbox source, GEvent event) { //_CODE_:isNut:402732:
  println("checkbox3 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isNut:402732:

public void lactoseClicked(GCheckbox source, GEvent event) { //_CODE_:isLactose:619520:
  println("checkbox4 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isLactose:619520:

public void vegetarianClicked(GCheckbox source, GEvent event) { //_CODE_:isVegetarian:332512:
  println("checkbox5 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isVegetarian:332512:

public void halalClicked(GCheckbox source, GEvent event) { //_CODE_:isHalal:618425:
  println("isHalal - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isHalal:618425:

public void veganClicked(GCheckbox source, GEvent event) { //_CODE_:isVegan:789138:
  println("isVegan - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:isVegan:789138:

public void confirm(GButton source, GEvent event) { //_CODE_:isConfirmed:360619:
  println("isConfirmed - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:isConfirmed:360619:

public void purpose_click1(GDropList source, GEvent event) { //_CODE_:pupose:796694:
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:pupose:796694:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Fuel Well", 0, 0, 240, 240, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  isPesc = new GCheckbox(window1, 120, 120, 120, 20);
  isPesc.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isPesc.setText("Pescetarian");
  isPesc.setOpaque(false);
  isPesc.addEventHandler(this, "pescClicked");
  isGluten = new GCheckbox(window1, 120, 140, 120, 20);
  isGluten.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isGluten.setText("Gluten-Free");
  isGluten.setOpaque(false);
  isGluten.addEventHandler(this, "glutenClicked");
  isNut = new GCheckbox(window1, 120, 160, 120, 20);
  isNut.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isNut.setText("Nut Allergy");
  isNut.setOpaque(false);
  isNut.addEventHandler(this, "nutClicked");
  isLactose = new GCheckbox(window1, 120, 180, 120, 20);
  isLactose.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isLactose.setText("Lactose Intolerant");
  isLactose.setOpaque(false);
  isLactose.addEventHandler(this, "lactoseClicked");
  isVegetarian = new GCheckbox(window1, 120, 60, 120, 20);
  isVegetarian.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isVegetarian.setText("Vegetarian");
  isVegetarian.setOpaque(false);
  isVegetarian.addEventHandler(this, "vegetarianClicked");
  isHalal = new GCheckbox(window1, 120, 100, 120, 20);
  isHalal.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isHalal.setText("Halal");
  isHalal.setOpaque(false);
  isHalal.addEventHandler(this, "halalClicked");
  isVegan = new GCheckbox(window1, 120, 80, 120, 20);
  isVegan.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  isVegan.setText("Vegan");
  isVegan.setOpaque(false);
  isVegan.addEventHandler(this, "veganClicked");
  isConfirmed = new GButton(window1, 80, 205, 80, 30);
  isConfirmed.setText("Submit");
  isConfirmed.addEventHandler(this, "confirm");
  pupose = new GDropList(window1, 10, 110, 90, 120, 5, 10);
  pupose.setItems(loadStrings("list_796694"), 0);
  pupose.addEventHandler(this, "purpose_click1");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GCheckbox isPesc; 
GCheckbox isGluten; 
GCheckbox isNut; 
GCheckbox isLactose; 
GCheckbox isVegetarian; 
GCheckbox isHalal; 
GCheckbox isVegan; 
GButton isConfirmed; 
GDropList pupose; 
